print("Enter Details for ID Card")
name=input("Enter your Name: ")
age=int(input("Enter your Age: "))
dept=input("Enter your Department: ")
print("---------------------")
print("-------ID Card-------")
print("Name:", name)
print("Age:", age)
print("Dept:",dept)
print("---------------------")
